<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <IsPackable>false</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="18.0.0" />
    <PackageReference Include="xunit" Version="2.9.3" />
    <PackageReference Include="xunit.runner.visualstudio" Version="3.1.4" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="Xunit" />
    <ProjectReference Include="../../src/RustyGoldbox.Core/RustyGoldbox.Core.csproj" />
    <ProjectReference Include="../../src/RustyGoldbox.Cli/RustyGoldbox.Cli.csproj" />
    <ProjectReference Include="../../src/RustyGoldbox.Game/RustyGoldbox.Game.csproj" />
  </ItemGroup>
</Project>
